### ISSUE TITLE
SA Map error

### ISSUE THREAD

**Issue by Mayhem365** [altonchaney/cosmere-maps#1]
Error received while switching from a longer book to a shorter book.

TypeError: Cannot read properties of undefined (reading 'chapter')
    at https://www.cosmeremaps.com/static/js/main.f3d64838.js:2:582766
    at Array.filter (<anonymous>)
    at https://www.cosmeremaps.com/static/js/main.f3d64838.js:2:582555
    at https://www.cosmeremaps.com/static/js/main.f3d64838.js:2:584210
    at Array.map (<anonymous>)
    at or (https://www.cosmeremaps.com/static/js/main.f3d64838.js:2:584186)
    at Si (https://www.cosmeremaps.com/static/js/main.f3d64838.js:2:280555)
    at Ps (https://www.cosmeremaps.com/static/js/main.f3d64838.js:2:292243)
    at xc (https://www.cosmeremaps.com/static/js/main.f3d64838.js:2:338678)
    at _l (https://www.cosmeremaps.com/static/js/main.f3d64838.js:2:326731)

**Comment by altonchaney** [comment]
I've added a potential fix for this issue in [this commit](https://github.com/altonchaney/cosmere-maps/commit/98243d4279186954457b3c6c7980a5dd93bfbc72) which should be live on the site now. Let me know if you are still having this issue!
